services:
  - type: web
    name: rudhra-3
    env: node
    branch: main
    repo: https://github.com/rudhachu/rudhra-3.git
    buildCommand: yarn install
    startCommand: node ./index.js
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MODE
        sync: false
      - key: PREFIX
        sync: false
      - key: SUDO
        sync: false
